server:
  servlet:
    context-path: /
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.173:3306/cheweibao?autoReconnect=true&useUnicode=yes&characterEncoding=UTF8
    username: admin
    password: admin1234
  messages:
    basename: i18n/admin/messages,i18n/common/messages

mybatis:
  mapper-locations: classpath:com/alibaba/dao/*Mapper.xml
pagehelper:
  auto-dialect: mysql
logging:
  level:
    com.alibaba.dao: debug

